stages:
  clean:
    cmd: python src/CleanData.py
    params:
    - clean.test
    deps:
    - data/test.csv
    - src/CleanData.py
  train:
    cmd: python src/TrainModel.py
    params:
    - train.kernal
    deps:
    - data/Cleansed/xTrainingSet.csv
  evaluate:
    cmd: python src/Evaluate.py
    deps:
    - data/Model/model.pkl
    metrics:
    - data/Evaluation/result.json:
         cache: false